
name: "Demo do Tech Talks"

on:
  workflow_dispatch:
    inputs:
      echoMessage:
        type: string
        required: false
        description: What should I echo?
      test:
        type: boolean
        required: false
        default: false
        description: Should I test?
      runJob2: 
        type: string
        required: false
        description: Input job2 to run job 2

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.echoMessage }}

  job2:
    runs-on: ubuntu-latest
    if: ${{ inputs.runJob2 == 'job2' }} 
    needs: job1
    steps:
      - run: echo job2

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job3
  
  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job4

  job5:
    runs-on: ubuntu-latest
    needs: [job3, job4]
    steps:
      - run: echo job5

  testing:
    runs-on: ubuntu-latest
    if: ${{ inputs.test }}
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm run test



