
name: "Demo do Tech Talks"

on:
  workflow_dispatch:
    inputs:
      echoMessage:
        type: string
        required: false
        description: What should I echo?

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.echoMessage }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo job2

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job3
  
  job4:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo job4

  job5:
    runs-on: ubuntu-latest
    needs: [job3, job4]
    steps:
      - run: echo job5


